### ISSUE TITLE
visualis二次开发文档

### ISSUE THREAD

**Issue by gs19931024** [WeBankFinTech/Visualis#28]
麻烦问一下，有没有visualis的二次开发指导文档或者开发文档？
当前需要对visualis进行二次开发，涉及前后台修改，没有找到类似的文档

**Comment by zhaomen** [comment]
同求，前端运行起来，一直在加载页面
![图片](https://user-images.githubusercontent.com/37888994/163310824-6c6c6d2e-d36b-44b1-9cdb-f06a7ef6e916.png)
